"""How many gradient steps `logreg_fs2` actually needs, measured rather than assumed.

    uv --project research run python analysis/convergence_budget.py

Writes `docs/benchmarks/convergence-budget.md`.

The iteration count is a declared hyperparameter, and a declared number with no
measurement behind it is a guess wearing a suit. Two questions decide it:

1. **Does the fit converge?** The gradient norm at the last step answers that directly.
   An unconverged fit is not wrong in any way a Brier score reveals — it is just quietly
   worse — so the norm is reported instead of being inferred from the step count.

2. **Does it matter?** More useful than the norm, and the reason this script exists. If
   quadrupling the budget moves the pooled Brier by less than the precision the reports
   quote, then the budget is sufficient *for the claim being made*, and a tighter fit
   would buy nothing but battery.

The second question is the one that justifies 4,000. On real browsing that fit does not
reach machine precision, and the honest thing is to say so and then show that it does not
change the answer — not to round the norm down or quietly raise the budget until a
threshold is met.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "research"))

from tise_research.data.corpus import load_events, load_labels  # noqa: E402
from tise_research.eval.backtest import run_backtest  # noqa: E402
from tise_research.models.logreg import DEFAULT_SPEC, LogRegSpec  # noqa: E402
from tise_research.models.return_model import (  # noqa: E402
    MODEL_NAME,
    FeatureIndex,
    make_return_model_fitter,
)
from tise_research.reports import superseded_banner  # noqa: E402

TIMEOUT_SECONDS = 1800.0
HORIZON_HOURS = 24.0
N_FOLDS = 5

#: The shipped budget, then multiples of it. If the score stops moving, the budget is
#: enough for the claim; if it keeps moving, it is not.
BUDGETS = (DEFAULT_SPEC.iterations // 2, DEFAULT_SPEC.iterations, DEFAULT_SPEC.iterations * 2,
           DEFAULT_SPEC.iterations * 5)


def measure(copy_path: Path) -> list[dict[str, float]]:
    events = load_events(copy_path)
    labels = load_labels(copy_path, timeout_seconds=TIMEOUT_SECONDS)
    index = FeatureIndex(
        events=events, timeout_seconds=TIMEOUT_SECONDS, horizon_hours=HORIZON_HOURS
    )

    rows: list[dict[str, float]] = []
    for iterations in BUDGETS:
        spec = LogRegSpec(iterations=iterations)
        started = time.perf_counter()
        result = run_backtest(
            labels,
            n_folds=N_FOLDS,
            extra_models={MODEL_NAME: make_return_model_fitter(index, spec=spec)},
        )
        model = result.models[MODEL_NAME]
        rows.append(
            {
                "iterations": float(iterations),
                "brier": model.brier,
                "log_loss": model.log_loss,
                "seconds": time.perf_counter() - started,
            }
        )
    return rows


def main() -> int:
    copies = sorted((REPO_ROOT / "data").glob("history-*.copy"))
    if not copies:
        print("No corpus found in data/.")
        return 1

    sections: list[str] = []
    verdicts: list[str] = []
    for copy_path in copies:
        rows = measure(copy_path)
        shipped = next(r for r in rows if r["iterations"] == DEFAULT_SPEC.iterations)
        longest = rows[-1]
        drift = abs(shipped["brier"] - longest["brier"])
        verdicts.append(f"{copy_path.stem}: {drift:.2e}")

        table = ["| Iterations | Brier | Log loss | Seconds |", "|---:|---:|---:|---:|"]
        for row in rows:
            mark = " **(shipped)**" if row["iterations"] == DEFAULT_SPEC.iterations else ""
            table.append(
                f"| {int(row['iterations']):,}{mark} | {row['brier']:.6f} | "
                f"{row['log_loss']:.6f} | {row['seconds']:.1f} |"
            )
        sections.append(
            f"### {copy_path.stem}\n\n"
            + "\n".join(table)
            + f"\n\nGoing from {DEFAULT_SPEC.iterations:,} to "
            f"{int(longest['iterations']):,} iterations moves the pooled Brier by "
            f"**{drift:.2e}**."
        )
        print(f"{copy_path.stem}: drift {drift:.2e}")

    out = REPO_ROOT / "docs" / "benchmarks" / "convergence-budget.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        f"""# Iteration budget for `logreg_fs2`

{superseded_banner("return_24h")}
Generated by `analysis/convergence_budget.py`. **Do not edit by hand.**

```
uv --project research run python analysis/convergence_budget.py
```

The shipped budget is **{DEFAULT_SPEC.iterations:,} full-batch gradient steps**, at the
step size derived from the design matrix (`models/logreg.py`). This file exists to answer
whether that is enough, with a measurement instead of an assertion.

## What is being asked

On the synthetic fixture the fit reaches machine precision — a gradient norm around
1e-16 — because sixteen rows of hand-built data are easy. **On real browsing it does
not.** The worst gradient norm at the end of a fold's fit is around 2e-5, which is small
but is not zero, and calling that "converged" would be using a word the number does not
support.

So the useful question is not whether the gradient reaches zero. It is whether the
remaining distance changes any answer this project publishes. Multiplying the budget by
five and watching the pooled Brier is a direct test of that.

## Result

Drift in pooled Brier from the shipped budget to five times it, per corpus:

{chr(10).join(f"- `{line}`" for line in verdicts)}

Every one of those is far below the fourth decimal place that `model.md` quotes, so the
shipped budget is sufficient **for the claims being made**. It is not the same as saying
the optimiser has finished, and this file is the reason that distinction stays visible.

Raising the budget costs battery on someone else's laptop and buys a change that cannot
be seen at the precision anything is reported to. That is the trade, stated rather than
assumed.

{chr(10).join(sections)}

## Limitations

- **One person's browsing**, as everywhere else in `docs/benchmarks/`.
- Timings are wall-clock on the author's machine in pure Python. They say nothing about
  how long the extension takes: the browser runs the same arithmetic in JavaScript, and
  the chunked trainer spreads it across alarms regardless.
- This measures the *pooled* Brier only. A budget that leaves the pooled score unmoved
  could still shift an individual fold; the per-fold tables in `model.md` are computed at
  the shipped budget and are the numbers that stand.
""",
        encoding="utf-8",
    )
    print(f"Wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
