"""Can an imported visit be recognised as a redirect hop without the transition bits?

**The problem.** Live collection gets `transitionQualifiers` from `webNavigation` and
drops redirect hops outright — T1 showed why: counting them pushed the median inter-visit
gap to about a second and inflated the domain count from 133 to 236. The
`chrome.history` API exposes `VisitItem.transition` as a *core type only*. There are no
qualifiers, so an import cannot make that call the same way.

That matters for the same reason D35 matters. If live drops redirects and import does
not, imported and observed events have different distributions, and every session-derived
feature computed across the boundary drifts as the import ages out under retention.

**The candidate.** `VisitItem.referringVisitId` *is* exposed, and so is `visitTime`. A
redirect hop is a visit whose referrer fired a moment earlier. So: flag a visit as a
redirect when it has a resolvable referrer and the gap to that referrer is at most some
threshold.

**Why this script exists.** That is a guess, and the history *file* holds the answer:
`visits.transition` there carries the real redirect bits. So the heuristic can be scored
against ground truth on a real corpus instead of being asserted. If it scores badly, the
right outcome is to record that and not ship it.

Aggregates only. No domain, URL or title is written anywhere by this script.
"""

from __future__ import annotations

import argparse
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from tise_research.data.chrome_history import REDIRECT_MASK, copy_history_db

#: Milliseconds. The extension sees `visitTime` in milliseconds, so the thresholds are
#: expressed in the units the shipped code would actually compare.
THRESHOLDS_MS = (50, 100, 250, 500, 1000, 2000, 5000)

_ROWS = """
SELECT v.id, v.visit_time, v.transition, v.from_visit
FROM visits AS v
ORDER BY v.visit_time
"""


@dataclass(frozen=True, slots=True)
class Row:
    visit_id: int
    visit_time_us: int
    transition: int
    from_visit: int


@dataclass(frozen=True, slots=True)
class Score:
    threshold_ms: int
    true_positive: int
    false_positive: int
    false_negative: int
    true_negative: int

    @property
    def precision(self) -> float | None:
        flagged = self.true_positive + self.false_positive
        return self.true_positive / flagged if flagged else None

    @property
    def recall(self) -> float | None:
        actual = self.true_positive + self.false_negative
        return self.true_positive / actual if actual else None

    @property
    def f1(self) -> float | None:
        p, r = self.precision, self.recall
        if p is None or r is None or p + r == 0:
            return None
        return 2 * p * r / (p + r)


def load_rows(db: Path) -> list[Row]:
    with sqlite3.connect(f"file:{db}?mode=ro", uri=True) as connection:
        return [Row(*row) for row in connection.execute(_ROWS)]


def score(rows: list[Row], threshold_ms: int) -> Score:
    """Score the heuristic against the redirect bits in the transition column."""
    times = {row.visit_id: row.visit_time_us for row in rows}
    limit_us = threshold_ms * 1000

    tp = fp = fn = tn = 0
    for row in rows:
        actual = bool(row.transition & REDIRECT_MASK)

        referrer = times.get(row.from_visit) if row.from_visit else None
        gap_us = row.visit_time_us - referrer if referrer is not None else None
        predicted = gap_us is not None and 0 <= gap_us <= limit_us

        if predicted and actual:
            tp += 1
        elif predicted and not actual:
            fp += 1
        elif actual:
            fn += 1
        else:
            tn += 1
    return Score(threshold_ms, tp, fp, fn, tn)


def referrer_resolvable_rate(rows: list[Row]) -> float | None:
    """Share of true redirect hops whose referring visit is present in the corpus.

    The import sees only the visits it fetched. A redirect hop whose referrer was not
    fetched cannot be judged at all, and the honest default there is to keep the event.
    This number is the ceiling on recall that the shipped code could ever reach.
    """
    present = set(row.visit_id for row in rows)
    redirects = [row for row in rows if row.transition & REDIRECT_MASK]
    if not redirects:
        return None
    resolvable = sum(1 for row in redirects if row.from_visit in present)
    return resolvable / len(redirects)


def render(browser: str, rows: list[Row], scores: list[Score]) -> str:
    total = len(rows)
    actual_redirects = sum(1 for row in rows if row.transition & REDIRECT_MASK)
    base_rate = actual_redirects / total if total else 0.0
    resolvable = referrer_resolvable_rate(rows)

    lines = [
        f"# Redirect heuristic — {browser}",
        "",
        "Generated by `analysis/redirect_heuristic.py`. Aggregates only.",
        "",
        "**Question:** the `chrome.history` API exposes no transition qualifiers, so an",
        "import cannot drop redirect hops the way live collection does. Can",
        "`referringVisitId` plus a time gap stand in for the missing bits?",
        "",
        "> **Superseded framing (D78).** The table below is a correct measurement of the",
        "> 50 ms rule against every row in the file, and it is not the question that",
        "> mattered. Chrome's history API hands over only the **end** of each redirect",
        "> chain, so most of these hops never reach the extension to be judged, and the",
        "> hops that do reach it have had their referrers withheld — which is why the",
        "> shipped rule fires on far fewer visits than the recall column suggests. See",
        "> `import-simulation-chrome.md`, which replays both stages.",
        "",
        f"- Visits in corpus: **{total:,}**",
        f"- Actual redirect hops (from the transition bits): **{actual_redirects:,}** "
        f"({base_rate:.1%})",
        f"- Redirect hops whose referrer is present: **{resolvable:.1%}**"
        if resolvable is not None
        else "- No redirect hops in this corpus.",
        "",
        "| gap ≤ | precision | recall | F1 | flagged | missed |",
        "|---:|---:|---:|---:|---:|---:|",
    ]

    def fmt(value: float | None) -> str:
        return f"{value:.3f}" if value is not None else "—"

    for s in scores:
        lines.append(
            f"| {s.threshold_ms} ms | {fmt(s.precision)} | {fmt(s.recall)} | {fmt(s.f1)} "
            f"| {s.true_positive + s.false_positive:,} | {s.false_negative:,} |"
        )

    lines += [
        "",
        "**Reading this table.** Precision is what matters more than recall. A false",
        "positive deletes a real navigation the person chose to make; a false negative",
        "leaves a redirect hop in, which is the status quo for imported data anyway.",
        "The recall column is capped by the resolvable-referrer rate above, because a",
        "hop whose referrer was never fetched cannot be judged at all.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--history", type=Path, required=True, help="history database")
    parser.add_argument("--browser", required=True, help="label for the report, e.g. Edge")
    parser.add_argument("--out", type=Path, default=Path("docs/benchmarks"))
    parser.add_argument("--data-dir", type=Path, default=Path("data"))
    args = parser.parse_args()

    slug = args.browser.strip().lower().replace(" ", "-")
    source = args.history
    if source.suffix != ".copy":
        source = copy_history_db(source, args.data_dir / f"history-{slug}.copy")

    rows = load_rows(source)
    scores = [score(rows, threshold) for threshold in THRESHOLDS_MS]

    args.out.mkdir(parents=True, exist_ok=True)
    report = args.out / f"redirect-heuristic-{slug}.md"
    report.write_text(render(args.browser, rows, scores), encoding="utf-8")
    print(f"wrote {report}")

    for s in scores:
        print(
            f"  {s.threshold_ms:>5} ms  precision "
            f"{s.precision if s.precision is None else round(s.precision, 3)}"
            f"  recall {s.recall if s.recall is None else round(s.recall, 3)}"
        )


if __name__ == "__main__":
    main()
